const ENV = {
    AWS_COGNITO_USER_POOL_ID: process.env.AWS_COGNITO_USER_POOL_ID,
    AWS_COGNITO_CLIENT_ID: process.env.AWS_COGNITO_CLIENT_ID,
    AWS_COGNITO_DOMAIN_URL: process.env.AWS_COGNITO_DOMAIN_URL
};
export default ENV;